CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE names (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  user_id INTEGER REFERENCES users(id)
);

CREATE TABLE votes (
  id SERIAL PRIMARY KEY,
  points INTEGER NOT NULL,
  user_id INTEGER REFERENCES users(id),
  name_id INTEGER REFERENCES names(id)
);